spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/The-Next-Bug/helm-charts.git
    targetRevision: HEAD


# Email Address for use in ClusterIssuers
email: "someone@example.com"

