# Missing email 
#
#
cluster-defaults:
  ingress-nginx:
    controller:
      service:
        annotations:
          service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
          service.beta.kubernetes.io/do-loadbalancer-name: "dev-cluster"
      config:
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
        use-proxy-protocol: "true"
