spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/The-Next-Bug/helm-charts.git
    targetRevision: HEAD


# Email Address for use in ClusterIssuers
email: "someone@example.com"

global:
  application:
    annotations:
      argocd.argoproj.io/sync-options: CreateNamespace=True Prune=True 

grafana:
  host: grafana.chrissalch.com

