{{- $root := . -}}
{{- range .Values.domains }}
{{- if .image }} 
{{- $tag := .image | replace "/" "-" | $root.Files.Get | trim }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-name" . }}
  labels:
    app: {{ include "kube-name" . }}

spec:
  replicas: {{ .replicas |  default 2 }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ include "kube-name" . }}

  template:
    metadata:
      labels:
        app: {{ include "kube-name" . }}

    spec:
      containers:
        - name: {{ include "kube-name" . }}
          image: "{{ .image }}{{- if $tag }}:{{ $tag }}{{- end -}}"
          ports:
            - containerPort: 80
          env:
          {{- if .env }}
          {{- toYaml .env | nindent 12 }}
          {{- end }}
      imagePullSecrets:
        - name: do-registry

{{- end }}
{{- end }}
