{{- $domainList := concat .Values.domains .Values.redirects -}} 
{{- range $domainList }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: {{ include "kube-name" . }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - secretName: "{{ .name }}-tls"
      hosts:
        - "{{ .name }}" 
        - "www.{{ .name }}"

  rules:
    - host: {{ .name }}
      http:
        paths:
          - backend:
              service:
                port:
                  number: 8080
                selector:
                  matchLabels:
                    {{ include "kube-name" . }}: true

    - host: "www.{{ .name }}"
      http:
        paths:
          - backend:
              service:
                name: "redirector"
                port:
                  number: 8080
    {{- range .rules }}
      {{ . | nindent 6 }}
    {{- end }}
{{- end }}
