{{- range .Values.domains }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - secretName: "{{ .name }}-tls"
      hosts:
        - "{{ .name }}"
        - "www.{{ .name }}"

  rules:
    - host: "{{ .name }}"
      http:
        paths:
          - backend:
              serviceName: "{{ .name}}"
              servicePort: 8080
    {{- range .rules }}
      {{ . | nindent 6 }}
    {{- end }}
{{- end }}
