{{- range .Values.domains  }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: {{ include "kube-name" . }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - secretName: "{{ .name }}-tls"
      hosts:
        - "{{ .name }}" 
        - "www.{{ .name }}"

  rules:
    - host: {{ .name }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "kube-name" . }} 
                port:
                  number: 8080

    - host: "www.{{ .name }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "redirector"
                port:
                  number: 8080
    {{- range .rules }}
      {{ . | nindent 6 }}
    {{- end }}
{{- end }}
{{- range .Values.redirects  }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: {{ include "kube-name" . }}
  labels:
    redirector: "true"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - secretName: "{{ .name }}-tls"
      hosts:
        - "{{ .name }}" 
        - "www.{{ .name }}"

  rules:
    - host: {{ .name }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "redirector"
                port:
                  number: 8080

    - host: "www.{{ .name }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "redirector"
                port:
                  number: 8080
    {{- range .rules }}
      {{ . | nindent 6 }}
    {{- end }}
{{- end }}
