{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "redirector"
  labels:
    app: "redirector"
data:
  # Default www redirect
  000_default.conf: |
    server {
      listen 8080;
      #server_name ~^(www\.|)(?<domain>.+)$;
      server_name: _;

      rewrite ^.*$ https://$domain$request_uri redirect;
    }

  {{- range .Values.redirects }}
  {{ .name }}.conf: |
    server {
      listen 8080;
      server_name ~^(www\.|){{ .name | replace "." "\\." }}$;

      rewrite ^.*$ {{ .target }} redirect;
    }
  {{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "redirector-nginx-conf"
  labels:
    app: "redirector"
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$host $remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for" '
                          '"$http_host"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "redirector" 
  labels:
    app: "redirector"

spec:
  replicas: {{ .replicas |  default 1 }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: "redirector"

  template:
    metadata:
      labels:
        app: "redirector"

    spec:
      containers:
        - name: "redirector"
          image: nginx 
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: templates
              mountPath: /etc/nginx/conf.d/ 
              readOnly: true
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: templates
          configMap:
            name: "redirector"
        - name: nginx-conf
          configMap:
            name: "redirector-nginx-conf"
---
apiVersion: v1
kind: Service
metadata:
  name: "redirector"
  labels:
    {{- range .Values.redirects }}
    {{ include "kube-name" . }}: true
    {{- end }}
spec:
  selector:
    app: "redirector"
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
