apiVersion: v1
kind: Service
metadata:
  name: "www-redirector"
spec:
  selector:
    app: "www-redirector"
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "www-redirector" 
  labels:
    app: "www-redirector"

spec:
  replicas: {{ .replicas |  default 1 }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: "www-redirector"

  template:
    metadata:
      labels:
        app: "www-redirector"

    spec:
      containers:
        - name: "www-redirector"
          image: registry.digitalocean.com/shelf/redirector
          env:
            - name: REDIRECTOR_TARGET
              value: "https://$domain$request_uri"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: do-registry

