{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "redirector"
  labels:
    app: "redirector"
data:
  # Default www redirect
  default.conf: |
    server {
      listen 8080;
      server_name ~^(www\.|)(?<domain>.+)$;

      rewrite ^.*$ https://$domain$request_uri redirect;
    }

  {{- range .Values.redirects }}
  {{ .name }}.conf: |
    server {
      listen: 8080;
      server_name ~^(www\.|)(?{{ .name }}.+)$;
    }
  {{- end}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "redirector" 
  labels:
    app: "redirector"

spec:
  replicas: {{ .replicas |  default 1 }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: "redirector"

  template:
    metadata:
      labels:
        app: "redirector"

    spec:
      containers:
        - name: "redirector"
          image: nginx 
          ports:
            - containerPort: {{ .Values.redirector_port }} 
          volumeMounts:
            - name: templates
              mountPath: /etc/nginx/conf.d/ 
              readonly: true
      volumes:
        - name: templates
          configMap:
            name: "rediretor"
---
apiVersion: v1
kind: Service
metadata:
  name: "redirector"
spec:
  selector:
    app: "redirector"
  porst:
    - protocol: TCP
      port: 8080
      targetPort: 8080
