{{- range .Values.domains }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-name" . }}
spec:
  selector:
    app: {{ include "kube-name" . }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
{{- end }}
