{{- range .Values.domains }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-name" . }}
spec:
  selector:
    app: {{ include "kube-name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 
{{- end }}
