{{- range .Values.domains }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .name }}-service"
spec:
  selector:
    app: "{{ .name }}-static"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 
{{- end }}
