domains:
  # Personal Site
  - name: "chrissalch.com"
    image: "registry.digitalocean.com/shelf/chrissalch-com"


  # The Next Bug Site
  - name: "thenextbug.com"
    image: "registry.digitalocean.com/shelf/the-next-bug"

redirects:
  # Some Old Domains 
  - name: "simplegomoku.com"
    target: https://thenextbug.com

  - name: "severeeyetrauma.com"
    target: https://thenextbug.com

  - name: "segmentnine.com"
    target: https://thenextbug.com

  - name: "seg9.com"
    target: https://thenextbug.com

  - name: "shinybitsnpieces.com"
    target: https://thenextbug.com
  
  - name: "kc5vzm.com"
    target: https://chrissalch.com

  - name: "arlaneenalra.com"
    target: https://chrissalch.com

  # The Erasable Man Generic redirect
  - name: "erasableman.com"
    target: https://chrissalch.com


