apiVersion: v2
name: ingress
description: Ingress config.
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: "3.3.0"


