apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager 
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    meta.helm.sh/release-namespace: "default"
  label:
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: "base-app"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    {{- include "global.application.annotations" . }}
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: "https://charts.jetstack.io" 
    targetRevision: "v1.9.1"
    chart: "cert-manager"

    helm:
      values: |
        # We need to make sure that CRDs are installed
        installCRDs: "true"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true 

