apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager 
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    {{- include "global.application.annotations" . }}
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: "https://charts.jetstack.io" 
    targetRevision: "1.5.3"
    chart: "cert-manager"

  helm:
    values: |
      # We need to make sure that CRDs are installed
      cert-manager:
        installCRDs: "true"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true 

