apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
  annotations:
    {{- include "global.application.annotations" . }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ingress 
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: "ingress"

    helm:
      values: |
        ingress-nginx:
          controller:
            service:
              annotations:
                service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
                service.beta.kubernetes.io/do-loadbalancer-name: "dev-cluster"
            config:
              use-forwarded-headers: "true"
              compute-full-forwarded-for: "true"
              use-proxy-protocol: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 

