apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ingress 
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
      #path: "argo-deploy"
    helm:
      repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      chartVersion: "3.3.0"

      values: |
        ingress-nginx:
          controller:
            service:
              annotations:
                service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
                service.beta.kubernetes.io/do-loadbalancer-name: "dev-cluster"
            config:
              use-forwarded-headers: "true"
              compute-full-forwarded-for: "true"
              use-proxy-protocol: "true"

