apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
  annotations:
    {{- include "global.application.annotations" . }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ingress 
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.0.2 
    chart: ingress-nginx

    helm:
      values: |
        controller:
          service:
            type: NodePort
            nodePorts:
              http: 30080
              https: 30443
          config:
            use-forwarded-headers: "true"
            compute-full-forwarded-for: "true"
            use-proxy-protocol: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: node-watcher 
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
# Need to move this to a more reasonable location later.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbac-node-watcher 
subjects:
- kind: Group
  name: node-watcher # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: node-watcher 
  apiGroup: rbac.authorization.k8s.io

