apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: {{ .Release.Namespace | quote }}
spec:
  acme:
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      -  dns01:
          digitalocean:
            tokenSecretRef:
              name: {{ .Values.digitalocean.token_name }}
              key: {{ .Values.digitalocean.token_key }}

