apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      -  dns01:
          digitalocean:
            tokenSecretRef:
              name: {{ .Values.digitalocean.token_name }}
              key: {{ .Values.digitalocean.token_key }}
